version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: unisur_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - eshop-network

  auth-service:
    build: .
    container_name: unisur_auth_service
    ports:
      - "8001:80"
    volumes:
      - ./services/auth-service:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_ecommerce_auth
      - DB_USER=root
      - DB_PASS=root_password
    depends_on:
      - mysql
    networks:
      - eshop-network

  catalog-service:
    build: .
    container_name: unisur_catalog_service
    ports:
      - "8002:80"
    volumes:
      - ./services/catalog-service:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_ecommerce_catalog
      - DB_USER=root
      - DB_PASS=root_password
    depends_on:
      - mysql
    networks:
      - eshop-network

  order-service:
    build: .
    container_name: unisur_order_service
    ports:
      - "8003:80"
    volumes:
      - ./services/order-service:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_ecommerce_orders
      - DB_USER=root
      - DB_PASS=root_password
      - AUTH_SERVICE_URL=http://auth-service
      - CATALOG_SERVICE_URL=http://catalog-service
    depends_on:
      - mysql
    networks:
      - eshop-network

  frontend:
    image: php:8.2-apache
    container_name: unisur_frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - eshop-network

networks:
  eshop-network:
    driver: bridge
